import type {Metadata} from 'next';
import StoreProvider from './StoreProvider';
import './layout.scss';
import NavigationBar from '@/components/Navigation/NavigationBar/NavigationBar';
import CartMenu from '@/components/Basket/CartMenu/CartMenu';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <NavigationBar />
          <CartMenu />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
